# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.5"
  # config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.33.12"

  config.vm.synced_folder "./scripts", "/home/vagrant/scripts"
  config.vm.synced_folder "../AWSLambda", "/home/vagrant/AWSLambda"
  config.vm.provision :shell, :path => "install.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
    vb.customize ['modifyvm', :id, '--cableconnected2', 'on']
  end
end
